//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class AttachFiles
{
    public int ID { get; set; }
    public Nullable<int> MessageID { get; set; }
    public Nullable<long> SizeFiles { get; set; }
    public string ContentType { get; set; }
    public string MimeType { get; set; }
    public string FileName { get; set; }
    public byte[] Filebinary { get; set; }

    public virtual Message Message { get; set; }
}

public partial class Member
{
    public Member()
    {
        this.Message = new HashSet<Message>();
        this.Send_Recive = new HashSet<Send_Recive>();
    }

    public int ID { get; set; }
    public string UserName { get; set; }
    public string Password { get; set; }
    public string DisplayName { get; set; }
    public int MemberGroupID { get; set; }
    public string LastLogin { get; set; }
    public string Tel { get; set; }
    public string Address { get; set; }
    public string Fax { get; set; }
    public string Email { get; set; }
    public string IPAddress { get; set; }
    public Nullable<int> Paren { get; set; }

    public virtual Memeber_Category Memeber_Category { get; set; }
    public virtual ICollection<Message> Message { get; set; }
    public virtual ICollection<Send_Recive> Send_Recive { get; set; }
}

public partial class Memeber_Category
{
    public Memeber_Category()
    {
        this.Member = new HashSet<Member>();
    }

    public int ID { get; set; }
    public string MemberGroupName { get; set; }

    public virtual ICollection<Member> Member { get; set; }
}

public partial class Message
{
    public Message()
    {
        this.AttachFiles = new HashSet<AttachFiles>();
        this.Send_Recive = new HashSet<Send_Recive>();
    }

    public int ID { get; set; }
    public string Title { get; set; }
    public string TextBody { get; set; }
    public int MemberID { get; set; }
    public string DateCreate { get; set; }
    public string SizeAttach { get; set; }
    public string ExpireDate { get; set; }
    public string IPAddress { get; set; }
    public string ShomareName { get; set; }
    public Nullable<bool> ISattach { get; set; }
    public Nullable<bool> TrashBox { get; set; }

    public virtual ICollection<AttachFiles> AttachFiles { get; set; }
    public virtual Member Member { get; set; }
    public virtual ICollection<Send_Recive> Send_Recive { get; set; }
}

public partial class Send_Recive
{
    public long ID { get; set; }
    public int MessegaeID { get; set; }
    public string DateView { get; set; }
    public Nullable<bool> Visit { get; set; }
    public Nullable<bool> TrashBox { get; set; }
    public string IPAddress { get; set; }
    public Nullable<int> Memeber_ReciveID { get; set; }

    public virtual Member Member { get; set; }
    public virtual Message Message { get; set; }
}

public partial class sysdiagrams
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class MemberList_Result
{
    public Nullable<int> Id { get; set; }
    public Nullable<int> ParentId { get; set; }
    public string MemberGroupName { get; set; }
    public Nullable<int> memberid { get; set; }
}

public partial class sp_helpdiagramdefinition_Result
{
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class sp_helpdiagrams_Result
{
    public string Database { get; set; }
    public string Name { get; set; }
    public int ID { get; set; }
    public string Owner { get; set; }
    public int OwnerID { get; set; }
}
